### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by a05031113**
楊昊宇（小羊）

url: http://3.209.230.175:3000
url: http://3.209.230.175:3000/attraction/6

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Sign out feature does not work.

**Comment by a05031113** [comment]
Did it work for second times? 
At first, I have this problem either for first time but second times work.
However, it doesn't happen since yesterday. 
I want to know when will the issue happen.

**Comment by cwpeng** [comment]
Your code cannot promise that reloading page action always after completing of signing out API.

**Comment by a05031113** [comment]
楊昊宇（小羊）

The problem that couldn't logout successfully every times is fetch didn't finish but reload first. 
So, I didn't detect the issue from server, which always return status=200.
I should check out who will run first next time... 

url: http://3.209.230.175:3000/
url: http://3.209.230.175:3000/attraction/6

**Review by cwpeng — APPROVED** [review]
Basically Done. Works OK.

But from your code, I know you do not handle JWT and programming details very well. For example, where your JWT stored? Cookie or local storage? And we do not need to setTimeout() before reload page.

**Pull request merged**
