### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by a05031113**
楊昊宇(小羊)

http://54.238.132.105:3000/api/attractions?page=1
http://54.238.132.105:3000/api/attractions?page=0&keyword=藝文館所
http://54.238.132.105:3000/api/attractions?page=0&keyword=北
http://54.238.132.105:3000/api/attractions/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Re-request review after you fix issue below

We nerver use SQL like this `SELECT * FROM attractions`. It's much better to use `LIMIT` in SQL to do pagination than do it in your own code.

**Comment by a05031113** [comment]
楊昊宇(小羊)

I have edited it by limit 12 data by each search. Please help to check again. 
Thanks!

http://54.238.132.105:3000/api/attractions?page=1
http://54.238.132.105:3000/api/attractions?page=0&keyword=藝文館所
http://54.238.132.105:3000/api/attractions?page=0&keyword=北
http://54.238.132.105:3000/api/attractions/10

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by a05031113** [comment]
I see. It's really on the right with a recycle symbol.

**Review by cwpeng — APPROVED** [review]
OK. Done. You are the Third One. :)

**Comment by a05031113** [comment]
Wow. Who is the first and second?

**Pull request merged**
