### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by a05031113**
楊昊宇（小羊）

http://3.209.230.175:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
I just get something like this, fix them.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Issues remains. Try to scroll down and up quickly.

**Comment by a05031113** [comment]
楊昊宇（小羊）

http://3.209.230.175:3000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
