### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by a05031113**
楊昊宇（小羊）

index: http://3.209.230.175:3000/
id=10: http://3.209.230.175:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Homepage layout is out of design in this version.
2. Line height of description text in attraction page should be a little larger.

**Comment by a05031113** [comment]
I'm not sure what is line-height larger? But I have fixed the stupid mistake of css.

index: http://3.209.230.175:3000/
id=10: http://3.209.230.175:3000/attraction/10

**Comment by cwpeng** [comment]
Line height of these text can be larger.
3 209 230 175_3000_attraction_2

**Comment by a05031113** [comment]
Wow! What a hawk eye! It's just slightly different between none setting line-height and setting.

**Comment by a05031113** [comment]
By the way, what's the widget you use for check line-height?

**Review by cwpeng — APPROVED** [review]
Good. Done. :)

Widget I use is my eyes.

**Pull request merged**
